### ISSUE TITLE
Install Error AzureADB2CProvider:Cannot insert duplicate key row

### ISSUE THREAD

**Issue by moorecreative** [intelequia/dnn.azureadb2cprovider#19]
I encountered an installer issue, though I am not sure it impacted the function of the authentication module as it completed installation enough to be listed within the Installed Authentication Systems list.

Scenario Environment - Evoq 9.4.4
Module Version - DNN Azure Active Directory B2C Provider 1.4.3
Module Version - DNN Azure Active Directory Provider 4.0.1

Install Error Event
In my testing scenario, I have the 4.0.1 DNN Azure Active Directory Provider is already installed in the DNN instance BEFORE the B2C Provider, however I do not think necessarily that it was involved in this specific install error message. I believe that the installer is twice trying to set a database record in the IX_Packages table. The following error is displayed during the installation log:

_AzureADB2CProvider:Cannot insert duplicate key row in object 'dbo.Packages' with unique index 'IZ_Packages'. The duplicate key value is (Intelequia,AzureADB2CProvider, Module, 1.4.3). The statement has been terminated._

Screenshots
![image](https://user-images.githubusercontent.com/5497943/82099200-bd37b800-96d4-11ea-8d1f-feba1e6ed56f.png)

![image](https://user-images.githubusercontent.com/5497943/82099207-c1fc6c00-96d4-11ea-8e49-9b4eccc76799.png)

**Comment by an-d-uu** [comment]
The issue seems to be with the 2 modules that have the same name in the AzureADB2CProvider.dnn file. Is there any reason we can't name the second one something like AzureADB2CProvider_Impersonation?

![image](https://user-images.githubusercontent.com/39595991/111377427-a0f70580-866e-11eb-90d5-ecdbf7393436.png)

**Comment by devtpsingh** [comment]
i am also facing the same issues, but whenever i refresh the page it's showing B2C provider and after configuration it's not working, please help me on this.

**Comment by davidjrh** [comment]
Hi, yes, sounds like an issue with the package name with the Impersonation module. I'm going to fix the manifest file as suggested. But I suspect that has nothing to do with the @devtpsingh is experiencing after the installation, since if you are not using the Impersonation module, you should be fine. What's the other error @devtpsingh ?

**Comment by devtpsingh** [comment]
i am using DNN Evoq Content v. 09.06.01. i need to authenticate using Azure B2C. i tried installing B2C Provider version https://github.com/intelequia/dnn.azureadb2cprovider/releases (Trying v1.4.6, v1.4.5, v1.4.3 and v1.4.2) all the versions but facing same issues. 
![image](https://user-images.githubusercontent.com/86398388/123242777-feb5ac00-d4ff-11eb-8096-4d62b4db4273.png)

**Comment by devtpsingh** [comment]
After above error I checked with refresh the page and found B2C provider is showing on DNN Evoq setting tab.
I configure with all details and trying to login with B2C user and it's redirect to me on Azure Portal and asking to username and password. After login it's redirect to me on website but Login and Register button still on my website. Redirect URL is
![image](https://user-images.githubusercontent.com/86398388/123243871-0a55a280-d501-11eb-929c-e0c58c62093e.png)

**Comment by davidjrh** [comment]
New release v1.4.7 solving this installation issue. 

For the other @devtpsingh I need more details. I see the redirected URL is missing the "/login". Did you put something on the ReturnURL field in the B2C settings in DNN? If you are not sure about that config setting, leave it empty to allow the redirection to the default /login page.

**Comment by devtpsingh** [comment]
Installation is done now in 1.4.7.

I am facing problem, Whenever I click on "Sign in with Azure B2C " 
![image](https://user-images.githubusercontent.com/86398388/123266426-a2f81c80-d519-11eb-99b4-cc6f5ddf35d2.png)
button it's going to Azure Portal and I filled my username and password and it's redirect at my website.
After redirecting at my website it's not showing display name of user and logout button. 

Redirect URL is : https://dev-dnn.allsober.com/Login?returnurl=%2f%3fstate%3ds%253dAzureB2C%253bp%253d0%253bc%253den-US%26code%3deyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..REAICtOjMJLAdNPB.o1t_hLNvP5wsl8bPHftHePgKenJrUXy44KJgVC-4r-YG37AxfDYBE2sH_fvHwmWuHsXxAftzfb_AOxVfq8ZSryscQENzSE2O8yePGrSgRBROfNoMD_XHByed3T0fNRXFS0gCGdIzn9zk9aeONgIV5Fas8EEcZsGUGblPGY41lnLMHHVqVvJCRYa75wjdp45tLBd5I1JFn5hzvbuktoYAF1rZMchPVCF8sa8zkSaYu6DvFT3dr2d6yNZIS_wY7Qp5vwDwnThUZHJq_dYi8BcWs4X91CmrxDeCBIn8W496WsOEAwOTT8F93y8aBCxjQvL46S4VxjQXX7a3B_eJoYKsJA3lzsJ8DX18jy3LE5VMmRkXv-dv5qATFLA-Ie_aGcMb4RYoCic7oA5iuCGBX9JZwek_L1O43QY-REKMpFS1VGF7teaWF8yFFg2obOOcTch87_zEH9ywrIRlNWTe1xPtfogj-scgUpnei6Oeuj6uNrVIzIgghRHC9QRHdoGifNb3JiOEpF0e4TnCiMcAZQgHuQU6W004p23ctZlaFDXch6nNEqRggxrY9LNGWoDkN541w5f_B8OX.9zNIQL7Wb11O9Z5Fv-1YDA

Image for your reference.
![image](https://user-images.githubusercontent.com/86398388/123267009-29146300-d51a-11eb-8670-0df2a0ae04a3.png)

B2C setting
![image](https://user-images.githubusercontent.com/86398388/123267183-595c0180-d51a-11eb-8deb-2d5f28d21852.png)

I checked in Database as well their are no record added for B2C user (aspnet_Users and Users table)

**Comment by davidjrh** [comment]
Hi @devtpsingh, seems your issue is not related to this issue subject, but let's try to figure out the reason:
1. Your screenshot above is not from the v1.4.7, probably because the javascript client files were cached by your browser from a previous install. Please clear the browser cache or open an inprivate browser session. You should see some of the latest settings such as the "Auto-Authorize Users After Login"
![image](https://user-images.githubusercontent.com/489976/123425228-c377b380-d5b9-11eb-9975-ed398bb34e17.png)
2. Check the log files under /portals/_default/logs to see if there is any auth error.

**Comment by davidjrh** [comment]
Going to close this issue since the subject has been resolved on v1.4.7. @devtpsingh please create another issue when having more information about your second error.

**Comment by devtpsingh** [comment]
yes, it's working for me.
thank you for help.
